name: test

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - run: npm install
      - run: npm run eslint
      - run: npm run build
      - uses: streamr-dev/streamr-docker-dev-action@v1.0.1
        with:
          services-to-start: mysql graph-deploy-streamregistry-subgraph trackers
      - run: npm run test
